### ISSUE TITLE
hash encoded to '%23'

### ISSUE THREAD

**Issue by ooopscc** [josh-/CloudyTabs#31]
Just as the title shows, hash in the url will be encoded to %23 html entity.

For reproduce this. You can open this in your safari on your iPhone, and check the url on OS X.
`http://www.nodebeginner.org/index-zh-cn.html#javascript-and-nodejs`

 Please fix it. Thanks.

**Comment by josh-** [comment]
Thanks for reporting this and sorry for the immense delay in getting back to you! I've isolated the issue with the incorrect encoding and will hopefully push an update in the next few days :+1:

**Comment by ooopscc** [comment]
👍👍👍

**Comment by core23** [comment]
The issue is still present if you try to open all tabs

**Comment by josh-** [comment]
Good pickup @core23! Reproduced on my and will have a look at fixing now 👍

**Comment by josh-** [comment]
Fixed in [Version 1.8](https://github.com/josh-/CloudyTabs/releases/tag/v1.8), however CloudyTabs won't prompt you to update because [GitLab pages is currently having issues](https://gitlab.com/gitlab-org/gitlab-pages/issues/88) so the updated Sparkle file isn't being served.

Until this is fixed, you can download the update by manually browsing to that release page 😄
