### ISSUE TITLE
Feature: Open tabs from self

### ISSUE THREAD

**Issue by intrepidsilence** [josh-/CloudyTabs#43]
It would be handy to be able to open all tabs from the device you are on.  I know this is an edge case but would make it easy to swap between using different browsers on the same system while maintaining your open tabs.  Just an idea.  What do you think?

**Comment by josh-** [comment]
Hi @intrepidsilence, thanks for raising this issue 🙌 

Initially CloudyTabs did list the tabs from the current computer that it was being run on (as is displayed in the [screenshot from the README](http://joshparnham.com/projects/cloudytabs/CloudyTabs.png)), however this was removed in #32.

Since you do mention that this is an edge case, what if I added a non-UI facing feature? Then, if a user wanted to list all their devices they could run a command in their terminal like:

    defaults write com.joshparnham.CloudyTabs ListAllDevices -bool true

Let me know what you think of this idea 😄

**Comment by intrepidsilence** [comment]
I like it.    Thanks!
  
  
  

  
  

  
  
>

**Comment by intrepidsilence** [comment]
Thanks for doing this Josh!  Looking forward to the release!
